#version: '3.9'

services:
  n8n:
    build: .  # Указывает на директорию с Dockerfile
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.n8n.rule=Host(`${SUBDOMAIN}.${DOMAIN_NAME}`)
      - traefik.http.routers.n8n.entrypoints=websecure
      - traefik.http.routers.n8n.tls=true
      - traefik.http.routers.n8n.tls.certresolver=le
      - traefik.http.services.n8n.loadbalancer.server.port=5678
      - traefik.http.middlewares.n8n-headers.headers.sslredirect=true
      - traefik.http.middlewares.n8n-headers.headers.stsincludesubdomains=true
      - traefik.http.middlewares.n8n-headers.headers.stspreload=true
      - traefik.http.middlewares.n8n-headers.headers.stsseconds=31536000
      - traefik.http.middlewares.n8n-headers.headers.browserxssfilter=true
      - traefik.http.middlewares.n8n-headers.headers.contenttypenosniff=true
      - traefik.http.routers.n8n.middlewares=n8n-headers
    environment:
      - N8N_HOST=${N8N_HOST}
      - N8N_PORT=${N8N_PORT}
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=https://${N8N_HOST}/
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_DATABASE=${DB_NAME}
      - DB_POSTGRESDB_USER=${DB_USER}
      - DB_POSTGRESDB_PASSWORD=${DB_PASSWORD}
      - DB_POSTGRESDB_HOST=${DB_HOST}
      - DB_POSTGRESDB_PORT=${DB_PORT}
#      - N8N_BASIC_AUTH_ACTIVE=true
#      - N8N_BASIC_AUTH_USER=${BASIC_AUTH_USER}
#      - N8N_BASIC_AUTH_PASSWORD=${BASIC_AUTH_PASSWORD}
    volumes:
      - n8n_data:/home/node/.n8n
volumes:
  traefik_data:
    external: true
  n8n_data:
